// Code generated by protoc-gen-go. DO NOT EDIT.
// source: remote/remote.proto

package remote

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Target               int32    `protobuf:"varint,2,opt,name=target,proto3" json:"target,omitempty"`
	Sender               int32    `protobuf:"varint,3,opt,name=sender,proto3" json:"sender,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_c646020309f17eac, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Message) GetTarget() int32 {
	if m != nil {
		return m.Target
	}
	return 0
}

func (m *Message) GetSender() int32 {
	if m != nil {
		return m.Sender
	}
	return 0
}

func init() {
	proto.RegisterType((*Message)(nil), "remote.Message")
}

func init() { proto.RegisterFile("remote/remote.proto", fileDescriptor_c646020309f17eac) }

var fileDescriptor_c646020309f17eac = []byte{
	// 171 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x4a, 0xcd, 0xcd,
	0x2f, 0x49, 0xd5, 0x87, 0x50, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0x6c, 0x10, 0x9e, 0x92,
	0x2f, 0x17, 0xbb, 0x6f, 0x6a, 0x71, 0x71, 0x62, 0x7a, 0xaa, 0x90, 0x10, 0x17, 0x4b, 0x4a, 0x62,
	0x49, 0xa2, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x4f, 0x10, 0x98, 0x2d, 0x24, 0xc6, 0xc5, 0x56, 0x92,
	0x58, 0x94, 0x9e, 0x5a, 0x22, 0xc1, 0xa4, 0xc0, 0xa8, 0xc1, 0x1a, 0x04, 0xe5, 0x81, 0xc4, 0x8b,
	0x53, 0xf3, 0x52, 0x52, 0x8b, 0x24, 0x98, 0x21, 0xe2, 0x10, 0x9e, 0x91, 0x35, 0x17, 0x5b, 0x10,
	0xd8, 0x60, 0x21, 0x43, 0x2e, 0xf6, 0xa0, 0xd4, 0xe4, 0xd4, 0xcc, 0xb2, 0x54, 0x21, 0x7e, 0x3d,
	0xa8, 0xd5, 0x50, 0x9b, 0xa4, 0xd0, 0x05, 0x94, 0x18, 0x34, 0x18, 0x0d, 0x18, 0x9d, 0xe4, 0xa2,
	0x64, 0xf4, 0xd3, 0x33, 0x4b, 0x32, 0x4a, 0x93, 0xf4, 0x92, 0xf3, 0x73, 0xf5, 0x33, 0xf2, 0x73,
	0x72, 0x2a, 0xcb, 0xf3, 0xf3, 0x53, 0xa0, 0x2e, 0x4f, 0x62, 0x03, 0x3b, 0xdd, 0x18, 0x10, 0x00,
	0x00, 0xff, 0xff, 0x6d, 0x12, 0x9e, 0x5c, 0xd1, 0x00, 0x00, 0x00,
}
